<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Approver;
use Illuminate\Support\Facades\Hash;

class ApproverSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $approvers = [
            [
                'approver_id' => 'acc09',
                'approver_name' => 'Nuri',
                'user_id' => 'acc09',
                'email' => 'nuriati@ptmbil.com',
                'password' => Hash::make('password123'),
                'olda_enabled' => false,
                'pr_authorized' => true,
                'pr_level' => 1,
                'pr_zero_price_allowed' => true,
                'pr_approval_style' => 'tick_1_pr',
                'pr_price_history' => false,
                'po_authorized' => false,
                'po_level' => 1,
                'po_approval_style' => 'tick_1_po',
                'po_min_limit' => 1.00,
                'po_max_limit' => 99999999.00,
                'is_active' => true,
            ],
            [
                'approver_id' => 'bgnkl',
                'approver_name' => 'BENGKEL',
                'user_id' => 'bgnkl',
                'email' => 'mulyadi@ptmbi.com',
                'password' => Hash::make('password123'),
                'olda_enabled' => false,
                'pr_authorized' => true,
                'pr_level' => 1,
                'pr_zero_price_allowed' => false,
                'pr_approval_style' => 'tick_1_pr',
                'pr_price_history' => true,
                'po_authorized' => true,
                'po_level' => 1,
                'po_approval_style' => 'tick_1_po',
                'po_min_limit' => 1.00,
                'po_max_limit' => 50000.00,
                'is_active' => true,
            ],
            [
                'approver_id' => 'mat03',
                'approver_name' => 'Marsih',
                'user_id' => 'mat03',
                'email' => 'marsih@ptmbil.com',
                'password' => Hash::make('password123'),
                'olda_enabled' => true,
                'pr_authorized' => true,
                'pr_level' => 2,
                'pr_zero_price_allowed' => false,
                'pr_approval_style' => 'tick_all_pr',
                'pr_price_history' => true,
                'po_authorized' => true,
                'po_level' => 2,
                'po_approval_style' => 'tick_all_po',
                'po_min_limit' => 50001.00,
                'po_max_limit' => 200000.00,
                'is_active' => true,
            ],
            [
                'approver_id' => 'mat04',
                'approver_name' => 'Christine',
                'user_id' => 'mat04',
                'email' => 'christine@ptmbil.com',
                'password' => Hash::make('password123'),
                'olda_enabled' => true,
                'pr_authorized' => true,
                'pr_level' => 1,
                'pr_zero_price_allowed' => true,
                'pr_approval_style' => 'tick_1_pr',
                'pr_price_history' => false,
                'po_authorized' => true,
                'po_level' => 1,
                'po_approval_style' => 'tick_1_po',
                'po_min_limit' => 1.00,
                'po_max_limit' => 100000.00,
                'is_active' => true,
            ],
            [
                'approver_id' => 'mat07',
                'approver_name' => 'Nikita',
                'user_id' => 'mat07',
                'email' => 'admin@ptmbil.com',
                'password' => Hash::make('password123'),
                'olda_enabled' => true,
                'pr_authorized' => true,
                'pr_level' => 3,
                'pr_zero_price_allowed' => true,
                'pr_approval_style' => 'tick_all_pr',
                'pr_price_history' => true,
                'po_authorized' => true,
                'po_level' => 3,
                'po_approval_style' => 'tick_all_po',
                'po_min_limit' => 200001.00,
                'po_max_limit' => 99999999.00,
                'is_active' => true,
            ],
            [
                'approver_id' => 'mat12',
                'approver_name' => 'Yufa',
                'user_id' => 'mat12',
                'email' => 'purchasing@ptmbi1.com',
                'password' => Hash::make('password123'),
                'olda_enabled' => false,
                'pr_authorized' => true,
                'pr_level' => 1,
                'pr_zero_price_allowed' => false,
                'pr_approval_style' => 'tick_1_pr',
                'pr_price_history' => true,
                'po_authorized' => false,
                'po_level' => 1,
                'po_approval_style' => 'tick_1_po',
                'po_min_limit' => 1.00,
                'po_max_limit' => 99999999.00,
                'is_active' => true,
            ],
            [
                'approver_id' => 'mat16',
                'approver_name' => 'Yuda',
                'user_id' => 'mat16',
                'email' => 'mbi.purchasing@ptmbi.com',
                'password' => Hash::make('password123'),
                'olda_enabled' => true,
                'pr_authorized' => true,
                'pr_level' => 2,
                'pr_zero_price_allowed' => false,
                'pr_approval_style' => 'tick_all_pr',
                'pr_price_history' => true,
                'po_authorized' => true,
                'po_level' => 2,
                'po_approval_style' => 'tick_all_po',
                'po_min_limit' => 100001.00,
                'po_max_limit' => 500000.00,
                'is_active' => true,
            ],
            [
                'approver_id' => 'mis04',
                'approver_name' => 'Nyoman',
                'user_id' => 'mis04',
                'email' => 'nwedasuharta@ptmbi1.com',
                'password' => Hash::make('password123'),
                'olda_enabled' => false,
                'pr_authorized' => false,
                'pr_level' => 1,
                'pr_zero_price_allowed' => false,
                'pr_approval_style' => 'tick_1_pr',
                'pr_price_history' => false,
                'po_authorized' => true,
                'po_level' => 1,
                'po_approval_style' => 'tick_1_po',
                'po_min_limit' => 1.00,
                'po_max_limit' => 25000.00,
                'is_active' => true,
            ],
            [
                'approver_id' => 'mis07',
                'approver_name' => 'Sakka',
                'user_id' => 'mis07',
                'email' => 'sagung@multiindustry1.com',
                'password' => Hash::make('password123'),
                'olda_enabled' => true,
                'pr_authorized' => true,
                'pr_level' => 3,
                'pr_zero_price_allowed' => true,
                'pr_approval_style' => 'tick_all_pr',
                'pr_price_history' => true,
                'po_authorized' => true,
                'po_level' => 3,
                'po_approval_style' => 'tick_all_po',
                'po_min_limit' => 500001.00,
                'po_max_limit' => 99999999.00,
                'is_active' => true,
            ],
            [
                'approver_id' => 'mkt05',
                'approver_name' => 'Endang',
                'user_id' => 'mkt05',
                'email' => 'endang@ptmbil.com',
                'password' => Hash::make('password123'),
                'olda_enabled' => false,
                'pr_authorized' => true,
                'pr_level' => 1,
                'pr_zero_price_allowed' => false,
                'pr_approval_style' => 'tick_1_pr',
                'pr_price_history' => false,
                'po_authorized' => false,
                'po_level' => 1,
                'po_approval_style' => 'tick_1_po',
                'po_min_limit' => 1.00,
                'po_max_limit' => 99999999.00,
                'is_active' => true,
            ],
            [
                'approver_id' => 'pa',
                'approver_name' => 'paa',
                'user_id' => 'pa',
                'email' => 'leonardo@prestigeatlantic.com.my',
                'password' => Hash::make('password123'),
                'olda_enabled' => false,
                'pr_authorized' => false,
                'pr_level' => 1,
                'pr_zero_price_allowed' => false,
                'pr_approval_style' => 'tick_1_pr',
                'pr_price_history' => false,
                'po_authorized' => false,
                'po_level' => 1,
                'po_approval_style' => 'tick_1_po',
                'po_min_limit' => 1.00,
                'po_max_limit' => 99999999.00,
                'is_active' => false,
            ],
        ];

        foreach ($approvers as $approverData) {
            Approver::updateOrCreate(
                ['approver_id' => $approverData['approver_id']],
                $approverData
            );
        }
    }
} 