<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CustomerAlternateAddressSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing data
        DB::table('customer_alternate_addresses')->truncate();
        
        // Sample data based on the customer account table
        $customers = [
            [
                'customer_name' => 'ABDULLAH BPK',
                'customer_code' => '000211-09',
                'salesperson_type' => 'S140',
                'currency' => 'Local',
                'currency_code' => 'IDR',
                'status' => 'Active',
                'address' => 'Jl. Pasar Minggu No. 45',
                'city' => 'Jakarta Selatan',
                'postal_code' => '12540',
                'phone' => '021-7867890',
                'email' => 'abdullah@example.com',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'customer_name' => 'ACEP SUNANDAR, BPK',
                'customer_code' => '000680-06',
                'salesperson_type' => 'S140',
                'currency' => 'Local',
                'currency_code' => 'IDR',
                'status' => 'Active',
                'address' => 'Jl. Raya Bogor Km. 30',
                'city' => 'Bogor',
                'postal_code' => '16720',
                'phone' => '0251-8654321',
                'email' => 'acep@example.com',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'customer_name' => 'ACHMAD JAMAL',
                'customer_code' => '000585-01',
                'salesperson_type' => 'S143',
                'currency' => 'Local',
                'currency_code' => 'IDR',
                'status' => 'Active',
                'address' => 'Jl. Merdeka No. 12',
                'city' => 'Bandung',
                'postal_code' => '40115',
                'phone' => '022-4231234',
                'email' => 'achmad.jamal@example.com',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'customer_name' => 'ACOSTA SUPER FOOD, PT',
                'customer_code' => '000293',
                'salesperson_type' => 'S143',
                'currency' => 'Local',
                'currency_code' => 'IDR',
                'status' => 'Active',
                'address' => 'Jl. Industri Selatan Blok JJ No. 10',
                'city' => 'Tangerang',
                'postal_code' => '15318',
                'phone' => '021-5559876',
                'email' => 'info@acostasuperfood.com',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'customer_name' => 'ADHITYA SETYABUDIHITA, PT',
                'customer_code' => '000502',
                'salesperson_type' => 'S143',
                'currency' => 'Local',
                'currency_code' => 'IDR',
                'status' => 'Active',
                'address' => 'Jl. Gatot Subroto Kav. 72',
                'city' => 'Jakarta Selatan',
                'postal_code' => '12780',
                'phone' => '021-5276543',
                'email' => 'contact@adhitya.co.id',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'customer_name' => 'ADIGUNA GEMILANG, PT',
                'customer_code' => '000851',
                'salesperson_type' => 'S140',
                'currency' => 'Local',
                'currency_code' => 'IDR',
                'status' => 'Active',
                'address' => 'Jl. Raya Serpong No. 8',
                'city' => 'Tangerang Selatan',
                'postal_code' => '15310',
                'phone' => '021-7564231',
                'email' => 'sales@adigunagemilang.com',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'customer_name' => 'ADEL LANGGENG, PT',
                'customer_code' => '000851',
                'salesperson_type' => 'S143',
                'currency' => 'Local',
                'currency_code' => 'IDR',
                'status' => 'Active',
                'address' => 'Jl. Tebet Raya No. 45',
                'city' => 'Jakarta Selatan',
                'postal_code' => '12810',
                'phone' => '021-8302145',
                'email' => 'info@adellanggeng.com',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'customer_name' => 'AGILITY INTERNATIONAL, PT',
                'customer_code' => '000004',
                'salesperson_type' => 'S118',
                'currency' => 'Local',
                'currency_code' => 'IDR',
                'status' => 'Active',
                'address' => 'Jl. MT Haryono Kav. 17',
                'city' => 'Jakarta Timur',
                'postal_code' => '13330',
                'phone' => '021-8507654',
                'email' => 'contact@agilityinternational.com',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'customer_name' => 'AGHNDO MAJU LESTARI, PT',
                'customer_code' => '000676',
                'salesperson_type' => 'S142',
                'currency' => 'Local',
                'currency_code' => 'IDR',
                'status' => 'Active',
                'address' => 'Jl. Raya Bekasi Km. 25',
                'city' => 'Bekasi',
                'postal_code' => '17132',
                'phone' => '021-8840123',
                'email' => 'sales@aghndo.co.id',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'customer_name' => 'AGRO MEGA PERKASA, PT',
                'customer_code' => '000839',
                'salesperson_type' => 'S211',
                'currency' => 'Local',
                'currency_code' => 'IDR',
                'status' => 'Active',
                'address' => 'Jl. Raya Bogor Km. 45',
                'city' => 'Bogor',
                'postal_code' => '16951',
                'phone' => '0251-8632541',
                'email' => 'info@agromegaperkasa.com',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'customer_name' => 'AGUNG KEMUNING WIJAYA, PT',
                'customer_code' => '000767',
                'salesperson_type' => 'S123',
                'currency' => 'Local',
                'currency_code' => 'IDR',
                'status' => 'Active',
                'address' => 'Jl. Sudirman Kav. 45',
                'city' => 'Jakarta Pusat',
                'postal_code' => '10210',
                'phone' => '021-5551234',
                'email' => 'contact@agungkemuning.com',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'customer_name' => 'AGUS',
                'customer_code' => '000212-24',
                'salesperson_type' => 'S211',
                'currency' => 'Local',
                'currency_code' => 'IDR',
                'status' => 'Active',
                'address' => 'Jl. Kebon Jeruk Raya No. 12',
                'city' => 'Jakarta Barat',
                'postal_code' => '11530',
                'phone' => '021-5304567',
                'email' => 'agus@example.com',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'customer_name' => 'AGUS IMAM MAKRUF',
                'customer_code' => '000861-03',
                'salesperson_type' => 'S140',
                'currency' => 'Local',
                'currency_code' => 'IDR',
                'status' => 'Active',
                'address' => 'Jl. Pahlawan No. 23',
                'city' => 'Semarang',
                'postal_code' => '50241',
                'phone' => '024-8412345',
                'email' => 'agus.imam@example.com',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'customer_name' => 'AGUS, BPK',
                'customer_code' => '000138-01',
                'salesperson_type' => 'S123',
                'currency' => 'Local',
                'currency_code' => 'IDR',
                'status' => 'Active',
                'address' => 'Jl. Veteran No. 45',
                'city' => 'Surabaya',
                'postal_code' => '60175',
                'phone' => '031-5678901',
                'email' => 'agus.bpk@example.com',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'customer_name' => 'AGUSTIN WULANDARI',
                'customer_code' => '000009-05',
                'salesperson_type' => 'S111',
                'currency' => 'Local',
                'currency_code' => 'IDR',
                'status' => 'Active',
                'address' => 'Jl. Ahmad Yani No. 78',
                'city' => 'Yogyakarta',
                'postal_code' => '55281',
                'phone' => '0274-567890',
                'email' => 'agustin.w@example.com',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'customer_name' => 'AGUSTINA INDAWATI',
                'customer_code' => '000774',
                'salesperson_type' => 'S123',
                'currency' => 'Local',
                'currency_code' => 'IDR',
                'status' => 'Active',
                'address' => 'Jl. Diponegoro No. 56',
                'city' => 'Malang',
                'postal_code' => '65145',
                'phone' => '0341-567890',
                'email' => 'agustina.i@example.com',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'customer_name' => 'AHMAD SUHYADI, BPK',
                'customer_code' => '000211-07',
                'salesperson_type' => 'S111',
                'currency' => 'Local',
                'currency_code' => 'IDR',
                'status' => 'Active',
                'address' => 'Jl. Imam Bonjol No. 34',
                'city' => 'Bandung',
                'postal_code' => '40115',
                'phone' => '022-4567890',
                'email' => 'ahmad.s@example.com',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'customer_name' => 'AKITA RAYA INDONESIA, PT',
                'customer_code' => '000701',
                'salesperson_type' => 'S111',
                'currency' => 'Local',
                'currency_code' => 'IDR',
                'status' => 'Active',
                'address' => 'Jl. TB Simatupang Kav. 22',
                'city' => 'Jakarta Selatan',
                'postal_code' => '12430',
                'phone' => '021-7891234',
                'email' => 'info@akitaraya.co.id',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'customer_name' => 'AKHUN KHASANI',
                'customer_code' => '000729',
                'salesperson_type' => 'S140',
                'currency' => 'Local',
                'currency_code' => 'IDR',
                'status' => 'Active',
                'address' => 'Jl. Cendrawasih No. 12',
                'city' => 'Cirebon',
                'postal_code' => '45118',
                'phone' => '0231-234567',
                'email' => 'akhun.k@example.com',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'customer_name' => 'AKAM PAMUNGKAS SENTOSA, PT',
                'customer_code' => '000648',
                'salesperson_type' => 'S143',
                'currency' => 'Local',
                'currency_code' => 'IDR',
                'status' => 'Active',
                'address' => 'Jl. Raya Cikarang Blok F No. 8',
                'city' => 'Bekasi',
                'postal_code' => '17530',
                'phone' => '021-8972345',
                'email' => 'contact@akampamungkas.co.id',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        // Insert data
        DB::table('customer_alternate_addresses')->insert($customers);
    }
}
