<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Customer;

class CustomerSeeder extends Seeder
{
    public function run()
    {
        $customers = [
            [
                'CODE' => '000211-08',
                'NAME' => 'ABDULLAH, BPK',
                'SLM' => 'S111',
                'TYPE' => 'N-Local',
                'CURRENCY' => 'IDR',
                'AC_STS' => 'A',
                'ADDRESS1' => 'Jakarta',
                'PERSON_CONTACT' => 'Abdullah',
                'TEL_NO' => '021-1234567',
                'FAX_NO' => '021-1234568',
                'EMAIL' => 'abdullah@email.com',
                'CREDIT_LIMIT' => 1000000.00,
                'TERM' => 30,
                'IND' => 'ID01',
                'AREA' => 'B110',
                'GROUP_' => '01',
                'NPWP' => '123456789012345',
                'CUST_TYPE' => 'C'
            ],
            [
                'CODE' => '000680-06',
                'NAME' => 'ACEP SUNANDAR, BPK',
                'SLM' => 'S140',
                'TYPE' => 'N-Local',
                'CURRENCY' => 'IDR',
                'AC_STS' => 'A',
                'ADDRESS1' => 'Bandung',
                'PERSON_CONTACT' => 'Acep Sunandar',
                'TEL_NO' => '022-2345678',
                'FAX_NO' => '022-2345679',
                'EMAIL' => 'acep@email.com',
                'CREDIT_LIMIT' => 2000000.00,
                'TERM' => 45,
                'IND' => 'ID02',
                'AREA' => 'B120',
                'GROUP_' => '02',
                'NPWP' => '234567890123456',
                'CUST_TYPE' => 'C'
            ],
            [
                'CODE' => '000585-01',
                'NAME' => 'ACHMAD JAMAL',
                'SLM' => 'S102',
                'TYPE' => 'N-Local',
                'CURRENCY' => 'IDR',
                'AC_STS' => 'A',
                'ADDRESS1' => 'Surabaya',
                'PERSON_CONTACT' => 'Achmad Jamal',
                'TEL_NO' => '031-3456789',
                'FAX_NO' => '031-3456790',
                'EMAIL' => 'achmad@email.com',
                'CREDIT_LIMIT' => 1500000.00,
                'TERM' => 30,
                'IND' => 'ID03',
                'AREA' => 'B130',
                'GROUP_' => '03',
                'NPWP' => '345678901234567',
                'CUST_TYPE' => 'C'
            ],
            [
                'CODE' => '000283',
                'NAME' => 'ACOSTA SUPER FOOD, PT',
                'SLM' => 'S103',
                'TYPE' => 'N-Local',
                'CURRENCY' => 'IDR',
                'AC_STS' => 'A',
                'ADDRESS1' => 'Medan',
                'PERSON_CONTACT' => 'Acosta Manager',
                'TEL_NO' => '061-4567890',
                'FAX_NO' => '061-4567891',
                'EMAIL' => 'acosta@email.com',
                'CREDIT_LIMIT' => 5000000.00,
                'TERM' => 60,
                'IND' => 'ID04',
                'AREA' => 'B140',
                'GROUP_' => '04',
                'NPWP' => '456789012345678',
                'CUST_TYPE' => 'C'
            ],
            [
                'CODE' => '000903',
                'NAME' => 'ADHITYA SERAYAKORITA, PT',
                'SLM' => 'S103',
                'TYPE' => 'N-Local',
                'CURRENCY' => 'IDR',
                'AC_STS' => 'A',
                'ADDRESS1' => 'Yogyakarta',
                'PERSON_CONTACT' => 'Adhitya Manager',
                'TEL_NO' => '0274-5678901',
                'FAX_NO' => '0274-5678902',
                'EMAIL' => 'adhitya@email.com',
                'CREDIT_LIMIT' => 3000000.00,
                'TERM' => 45,
                'IND' => 'ID05',
                'AREA' => 'B150',
                'GROUP_' => '05',
                'NPWP' => '567890123456789',
                'CUST_TYPE' => 'C'
            ],
            [
                'CODE' => '000507',
                'NAME' => 'ADIKARYA GEMILANG',
                'SLM' => 'S140',
                'TYPE' => 'N-Local',
                'CURRENCY' => 'IDR',
                'AC_STS' => 'A',
                'ADDRESS1' => 'Semarang',
                'PERSON_CONTACT' => 'Adikarya Owner',
                'TEL_NO' => '024-6789012',
                'FAX_NO' => '024-6789013',
                'EMAIL' => 'adikarya@email.com',
                'CREDIT_LIMIT' => 2500000.00,
                'TERM' => 30,
                'IND' => 'ID06',
                'AREA' => 'B160',
                'GROUP_' => '06',
                'NPWP' => '678901234567890',
                'CUST_TYPE' => 'C'
            ],
            [
                'CODE' => '000581',
                'NAME' => 'AGEL LANGGENG, PT',
                'SLM' => 'S143',
                'TYPE' => 'N-Local',
                'CURRENCY' => 'IDR',
                'AC_STS' => 'A',
                'ADDRESS1' => 'Makassar',
                'PERSON_CONTACT' => 'Agel Manager',
                'TEL_NO' => '0411-7890123',
                'FAX_NO' => '0411-7890124',
                'EMAIL' => 'agel@email.com',
                'CREDIT_LIMIT' => 4000000.00,
                'TERM' => 60,
                'IND' => 'ID07',
                'AREA' => 'B170',
                'GROUP_' => '07',
                'NPWP' => '789012345678901',
                'CUST_TYPE' => 'C'
            ],
            [
                'CODE' => '000004',
                'NAME' => 'AGILITY INTERNATIONAL, PT',
                'SLM' => 'S118',
                'TYPE' => 'Y-Foreign',
                'CURRENCY' => 'USD',
                'AC_STS' => 'A',
                'ADDRESS1' => 'Singapore',
                'PERSON_CONTACT' => 'Agility Manager',
                'TEL_NO' => '+65-8901234',
                'FAX_NO' => '+65-8901235',
                'EMAIL' => 'agility@email.com',
                'CREDIT_LIMIT' => 10000000.00,
                'TERM' => 90,
                'IND' => 'ID08',
                'AREA' => 'B180',
                'GROUP_' => '08',
                'NPWP' => '890123456789012',
                'CUST_TYPE' => 'C'
            ],
            [
                'CODE' => '000676',
                'NAME' => 'AGRINDO MAJU LESTARI, PT',
                'SLM' => 'S142',
                'TYPE' => 'N-Local',
                'CURRENCY' => 'IDR',
                'AC_STS' => 'A',
                'ADDRESS1' => 'Palembang',
                'PERSON_CONTACT' => 'Agrindo Manager',
                'TEL_NO' => '0711-9012345',
                'FAX_NO' => '0711-9012346',
                'EMAIL' => 'agrindo@email.com',
                'CREDIT_LIMIT' => 3500000.00,
                'TERM' => 45,
                'IND' => 'ID09',
                'AREA' => 'B190',
                'GROUP_' => '09',
                'NPWP' => '901234567890123',
                'CUST_TYPE' => 'C'
            ],
            [
                'CODE' => '000839',
                'NAME' => 'AGRO MEGA PERKASA, PT',
                'SLM' => 'S111',
                'TYPE' => 'N-Local',
                'CURRENCY' => 'IDR',
                'AC_STS' => 'A',
                'ADDRESS1' => 'Bali',
                'PERSON_CONTACT' => 'Agro Manager',
                'TEL_NO' => '0361-0123456',
                'FAX_NO' => '0361-0123457',
                'EMAIL' => 'agro@email.com',
                'CREDIT_LIMIT' => 6000000.00,
                'TERM' => 60,
                'IND' => 'ID10',
                'AREA' => 'B200',
                'GROUP_' => '10',
                'NPWP' => '012345678901234',
                'CUST_TYPE' => 'C'
            ]
        ];

        foreach ($customers as $customer) {
            Customer::updateOrCreate(
                ['CODE' => $customer['CODE']],
                $customer
            );
        }
    }
}
