<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\ProductDesign;

class ProductDesignSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $productDesigns = [
            [
                'pd_code' => 'APP',
                'pd_name' => 'APP',
                'pd_design_type' => 'T-Trading',
                'idc' => 'NA',
                'product' => '005',
                'joint' => 'No',
                'joint_to_print' => 'No',
                'pcs_to_joint' => '0',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'N/A',
                'print_flute' => 'No',
                'input_weight' => 'Yes',
    
            ],
            [
                'pd_code' => 'BO',
                'pd_name' => 'BO/BO',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0510',
                'product' => '001',
                'joint' => 'No',
                'joint_to_print' => 'No',
                'pcs_to_joint' => '0',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'BO DJ',
                'pd_name' => 'BO/BO DOUBLE JOINT',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0510J2',
                'product' => '001',
                'joint' => 'Yes',
                'joint_to_print' => 'Yes',
                'pcs_to_joint' => '2',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'BO/B1',
                'pd_name' => 'B1/BO FLIP BANAR',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0200B',
                'product' => '001',
                'joint' => 'No',
                'joint_to_print' => 'No',
                'pcs_to_joint' => '0',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'BO/B1 4J',
                'pd_name' => 'BO/B1 4 JOINT',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0204B',
                'product' => '001',
                'joint' => 'Yes',
                'joint_to_print' => 'Yes',
                'pcs_to_joint' => '4',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'No',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'BO/B1 DJ',
                'pd_name' => 'BO/B1 DOUBLE JOINT',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0202B',
                'product' => '001',
                'joint' => 'Yes',
                'joint_to_print' => 'Yes',
                'pcs_to_joint' => '2',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'B1',
                'pd_name' => 'REGULAR BOX',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0201',
                'product' => '001',
                'joint' => 'No',
                'joint_to_print' => 'No',
                'pcs_to_joint' => '0',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'B1 4J',
                'pd_name' => 'B1 4 JOINT',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0201a',
                'product' => '001',
                'joint' => 'Yes',
                'joint_to_print' => 'Yes',
                'pcs_to_joint' => '4',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'B1 4J 2C',
                'pd_name' => 'B1 4 JOINT + CREASING',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0201s',
                'product' => '001',
                'joint' => 'Yes',
                'joint_to_print' => 'Yes',
                'pcs_to_joint' => '4',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'B1 DJ',
                'pd_name' => 'B1 DOUBLE JOINT',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0201J2',
                'product' => '001',
                'joint' => 'Yes',
                'joint_to_print' => 'Yes',
                'pcs_to_joint' => '2',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'B1 DJ FR',
                'pd_name' => 'B1 DOUBLE JOINT FLUTE REVERSE',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0201R',
                'product' => '001',
                'joint' => 'Yes',
                'joint_to_print' => 'Yes',
                'pcs_to_joint' => '2',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Reverse',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'B1 DJ+',
                'pd_name' => 'B1 DOUBLE JOINT + CREASING',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0201s',
                'product' => '001',
                'joint' => 'Yes',
                'joint_to_print' => 'Yes',
                'pcs_to_joint' => '2',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'B1+1CR',
                'pd_name' => 'B1+1CREASING',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0201s',
                'product' => '001',
                'joint' => 'No',
                'joint_to_print' => 'No',
                'pcs_to_joint' => '0',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'B1+1CRDJ',
                'pd_name' => 'B1+1CREASING DOUBLE JOINT',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0201J2',
                'product' => '001',
                'joint' => 'Yes',
                'joint_to_print' => 'Yes',
                'pcs_to_joint' => '2',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'B1+1CR-H',
                'pd_name' => 'B1+1CREASING+HOLE',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0201s',
                'product' => '001',
                'joint' => 'No',
                'joint_to_print' => 'No',
                'pcs_to_joint' => '0',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'B1-DC',
                'pd_name' => 'B1 DIECUT',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0201DC',
                'product' => '001',
                'joint' => 'No',
                'joint_to_print' => 'No',
                'pcs_to_joint' => '0',
                'score' => 'No',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'No',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'B1-DC DJ',
                'pd_name' => 'B1 DIECUT DOUBLE JOINT',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0201DCJ2',
                'product' => '001',
                'joint' => 'Yes',
                'joint_to_print' => 'No',
                'pcs_to_joint' => '2',
                'score' => 'No',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'No',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'B1-H',
                'pd_name' => 'B1+HOLE',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0201h',
                'product' => '001',
                'joint' => 'No',
                'joint_to_print' => 'No',
                'pcs_to_joint' => '0',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'B2',
                'pd_name' => 'B2',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0202',
                'product' => '001',
                'joint' => 'No',
                'joint_to_print' => 'No',
                'pcs_to_joint' => '0',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'B2 DJ',
                'pd_name' => 'B2 DOUBLE JOINT',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0202J2',
                'product' => '001',
                'joint' => 'Yes',
                'joint_to_print' => 'Yes',
                'pcs_to_joint' => '2',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'B3',
                'pd_name' => 'B3',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0203',
                'product' => '001',
                'joint' => 'No',
                'joint_to_print' => 'No',
                'pcs_to_joint' => '0',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'B3 DJ',
                'pd_name' => 'B3 DOUBLE JOINT',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0203J2',
                'product' => '001',
                'joint' => 'Yes',
                'joint_to_print' => 'Yes',
                'pcs_to_joint' => '2',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'B4',
                'pd_name' => 'B4',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0204',
                'product' => '001',
                'joint' => 'No',
                'joint_to_print' => 'No',
                'pcs_to_joint' => '0',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'B5',
                'pd_name' => 'B5',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0205',
                'product' => '001',
                'joint' => 'No',
                'joint_to_print' => 'No',
                'pcs_to_joint' => '0',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'B6',
                'pd_name' => 'B6',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0206',
                'product' => '001',
                'joint' => 'No',
                'joint_to_print' => 'No',
                'pcs_to_joint' => '0',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'B7',
                'pd_name' => 'B7',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0207',
                'product' => '001',
                'joint' => 'No',
                'joint_to_print' => 'No',
                'pcs_to_joint' => '0',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'B8',
                'pd_name' => 'B8',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0208',
                'product' => '001',
                'joint' => 'No',
                'joint_to_print' => 'No',
                'pcs_to_joint' => '0',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'B9',
                'pd_name' => 'B9',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0209',
                'product' => '001',
                'joint' => 'No',
                'joint_to_print' => 'No',
                'pcs_to_joint' => '0',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'BALI',
                'pd_name' => 'BOX BALI',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0210',
                'product' => '001',
                'joint' => 'No',
                'joint_to_print' => 'No',
                'pcs_to_joint' => '0',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'BB',
                'pd_name' => 'BOX BERGELOMBANG',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0211',
                'product' => '001',
                'joint' => 'No',
                'joint_to_print' => 'No',
                'pcs_to_joint' => '0',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'BF',
                'pd_name' => 'BOTTOM FLAP',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0212',
                'product' => '001',
                'joint' => 'No',
                'joint_to_print' => 'No',
                'pcs_to_joint' => '0',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'BK',
                'pd_name' => 'BOX KECIL',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0213',
                'product' => '001',
                'joint' => 'No',
                'joint_to_print' => 'No',
                'pcs_to_joint' => '0',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'BL',
                'pd_name' => 'BLANK',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0214',
                'product' => '001',
                'joint' => 'No',
                'joint_to_print' => 'No',
                'pcs_to_joint' => '0',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'BM',
                'pd_name' => 'BOX METER',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0215',
                'product' => '001',
                'joint' => 'No',
                'joint_to_print' => 'No',
                'pcs_to_joint' => '0',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'BMA',
                'pd_name' => 'BOX MAJALAH',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0216',
                'product' => '001',
                'joint' => 'No',
                'joint_to_print' => 'No',
                'pcs_to_joint' => '0',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'BN',
                'pd_name' => 'BOX NON STANDARD',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0217',
                'product' => '001',
                'joint' => 'No',
                'joint_to_print' => 'No',
                'pcs_to_joint' => '0',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'BS',
                'pd_name' => 'BOX STANDARD',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0218',
                'product' => '001',
                'joint' => 'No',
                'joint_to_print' => 'No',
                'pcs_to_joint' => '0',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'BSA',
                'pd_name' => 'BOX SAMPUL',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0219',
                'product' => '001',
                'joint' => 'No',
                'joint_to_print' => 'No',
                'pcs_to_joint' => '0',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'C1',
                'pd_name' => 'CREASING 1',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0220',
                'product' => '001',
                'joint' => 'No',
                'joint_to_print' => 'No',
                'pcs_to_joint' => '0',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'C2',
                'pd_name' => 'CREASING 2',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0221',
                'product' => '001',
                'joint' => 'No',
                'joint_to_print' => 'No',
                'pcs_to_joint' => '0',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
            [
                'pd_code' => 'CF',
                'pd_name' => 'CENTER FLAP',
                'pd_design_type' => 'M-Manufacture',
                'idc' => '0222',
                'product' => '001',
                'joint' => 'No',
                'joint_to_print' => 'No',
                'pcs_to_joint' => '0',
                'score' => 'Yes',
                'slot' => 'No',
                'flute_style' => 'Normal',
                'print_flute' => 'Yes',
                'input_weight' => 'No',
                
            ],
        ];

        // Using updateOrInsert to avoid duplicate entries based on 'pd_code'
        foreach ($productDesigns as $design) {
            // Ensure alt name is populated; default to main name if not explicitly set
            if (!isset($design['pd_alt_name'])) {
                $design['pd_alt_name'] = $design['pd_name'] ?? null;
            }
            ProductDesign::updateOrInsert(['pd_code' => $design['pd_code']], $design);
        }
    }
} 