<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class SalespersonTeamSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('salesperson_teams')->truncate();
        
        $now = Carbon::now();
        
        $salespersonTeams = [
            [
                's_person_code' => 'S101',
                'salesperson_name' => 'ABENG',
                'st_code' => '01',
                'sales_team_name' => 'MBI',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S102',
                'salesperson_name' => 'AGUNG',
                'st_code' => '01',
                'sales_team_name' => 'MBI',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S103',
                'salesperson_name' => 'EKO',
                'st_code' => '01',
                'sales_team_name' => 'MBI',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S104',
                'salesperson_name' => 'ELIAS',
                'st_code' => '01',
                'sales_team_name' => 'MBI',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S105',
                'salesperson_name' => 'FEBBY',
                'st_code' => '01',
                'sales_team_name' => 'MBI',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S106',
                'salesperson_name' => 'HASAN',
                'st_code' => '01',
                'sales_team_name' => 'MBI',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S107',
                'salesperson_name' => 'HENGKI',
                'st_code' => '01',
                'sales_team_name' => 'MBI',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S108',
                'salesperson_name' => 'IN HOUSE',
                'st_code' => '02',
                'sales_team_name' => 'MANAGEMENT LOCAL',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S109',
                'salesperson_name' => 'IN HOUSE FREELANCE JOHO',
                'st_code' => '02',
                'sales_team_name' => 'MANAGEMENT LOCAL',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S110',
                'salesperson_name' => 'INSAN SIE',
                'st_code' => '01',
                'sales_team_name' => 'MBI',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S111',
                'salesperson_name' => 'EMOSI TV',
                'st_code' => '01',
                'sales_team_name' => 'MBI',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S112',
                'salesperson_name' => 'KUSNIAWAN',
                'st_code' => '01',
                'sales_team_name' => 'MBI',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S113',
                'salesperson_name' => 'MARTIN',
                'st_code' => '01',
                'sales_team_name' => 'MBI',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S114',
                'salesperson_name' => 'MELI',
                'st_code' => '01',
                'sales_team_name' => 'MBI',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S115',
                'salesperson_name' => 'MELINA',
                'st_code' => '01',
                'sales_team_name' => 'MBI',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S116',
                'salesperson_name' => 'MULTI NATIONAL COMPANY',
                'st_code' => '03',
                'sales_team_name' => 'MANAGEMENT MNC',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S117',
                'salesperson_name' => 'RICKY',
                'st_code' => '01',
                'sales_team_name' => 'MBI',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S118',
                'salesperson_name' => 'ROBERT PURBA',
                'st_code' => '01',
                'sales_team_name' => 'MBI',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S119',
                'salesperson_name' => 'STEAN',
                'st_code' => '01',
                'sales_team_name' => 'MBI',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S120',
                'salesperson_name' => 'TONI',
                'st_code' => '01',
                'sales_team_name' => 'MBI',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S121',
                'salesperson_name' => 'TOREY',
                'st_code' => '01',
                'sales_team_name' => 'MBI',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S122',
                'salesperson_name' => 'TUN WIE',
                'st_code' => '01',
                'sales_team_name' => 'MBI',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S123',
                'salesperson_name' => 'YANTO',
                'st_code' => '01',
                'sales_team_name' => 'MBI',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S124',
                'salesperson_name' => 'PETER SIE',
                'st_code' => '02',
                'sales_team_name' => 'MANAGEMENT LOCAL',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S125',
                'salesperson_name' => 'INHOUSE FREELANCE SUFATO',
                'st_code' => '02',
                'sales_team_name' => 'MANAGEMENT LOCAL',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S126',
                'salesperson_name' => 'INHOUSE FREELANCE ROBBY',
                'st_code' => '02',
                'sales_team_name' => 'MANAGEMENT LOCAL',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S127',
                'salesperson_name' => 'PINKY',
                'st_code' => '01',
                'sales_team_name' => 'MBI',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S128',
                'salesperson_name' => 'MULTI NATIONAL COMPANY',
                'st_code' => '03',
                'sales_team_name' => 'MANAGEMENT MNC',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S129',
                'salesperson_name' => 'MULTI NATIONAL COMPANY D1',
                'st_code' => '03',
                'sales_team_name' => 'MANAGEMENT MNC',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S130',
                'salesperson_name' => 'MULTI NATIONAL COMPANY D2',
                'st_code' => '03',
                'sales_team_name' => 'MANAGEMENT MNC',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S131',
                'salesperson_name' => 'MULTI NATIONAL COMPANY D3',
                'st_code' => '03',
                'sales_team_name' => 'MANAGEMENT MNC',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S132',
                'salesperson_name' => 'MULTI NATIONAL COMPANY AV',
                'st_code' => '03',
                'sales_team_name' => 'MANAGEMENT MNC',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S133',
                'salesperson_name' => 'INHOUSE LOCAL',
                'st_code' => '02',
                'sales_team_name' => 'MANAGEMENT LOCAL',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S134',
                'salesperson_name' => 'INHOUSE FREELANCE ROBBY',
                'st_code' => '02',
                'sales_team_name' => 'MANAGEMENT LOCAL',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S135',
                'salesperson_name' => 'INHOUSE FREELANCE YULI',
                'st_code' => '02',
                'sales_team_name' => 'MANAGEMENT LOCAL',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S136',
                'salesperson_name' => 'INHOUSE JOGJATV',
                'st_code' => '02',
                'sales_team_name' => 'MANAGEMENT LOCAL',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S137',
                'salesperson_name' => 'INHOUSE FREELANCE YULI',
                'st_code' => '02',
                'sales_team_name' => 'MANAGEMENT LOCAL',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S138',
                'salesperson_name' => 'INHOUSE JOGJATV',
                'st_code' => '02',
                'sales_team_name' => 'MANAGEMENT LOCAL',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S139',
                'salesperson_name' => 'INHOUSE',
                'st_code' => '02',
                'sales_team_name' => 'MANAGEMENT LOCAL',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S140',
                'salesperson_name' => 'FERSIAN',
                'st_code' => '01',
                'sales_team_name' => 'MBI',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                's_person_code' => 'S141',
                'salesperson_name' => 'GABRIELA (MEGA)',
                'st_code' => '02',
                'sales_team_name' => 'MANAGEMENT LOCAL',
                'sales_team_position' => 'E-Executive',
                'status' => 'Act',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('salesperson_teams')->insert($salespersonTeams);
    }
} 