<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class WorkOrderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $workOrders = [
            [
                'wo_number' => '06-2025-01706',
                'so_number' => '06-2025-02264',
                'customer_name' => 'DIA RUPIAH',
                'plan_qty' => 50000.00,
                'due_date' => '2025-06-30',
                'status' => 'Active',
                'wo_status' => 'Active',
                'so_status' => 'Outstanding',
                'acr_number' => '000506',
                'mcs_number' => '0063879',
                'model' => '22819',
                'comp_number' => 'Main',
                'part_number' => 'BOX',
                'pd' => 'PUNCH',
                'pcs_per_unit' => '1/Pcs',
                'ied_x' => '0',
                'ied_y' => '0',
                'completed_qty' => 0.00,
                'start_date' => '2025-06-01',
                'description' => 'Box production for DIA RUPIAH',
                'created_by' => 'System',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'wo_number' => '06-2025-01703',
                'so_number' => '06-2025-02253',
                'customer_name' => 'DIA RUPIAH',
                'plan_qty' => 50000.00,
                'due_date' => '2025-06-28',
                'status' => 'Active',
                'wo_status' => 'Active',
                'so_status' => 'Outstanding',
                'acr_number' => '000506',
                'mcs_number' => '0063879',
                'model' => '22819',
                'comp_number' => 'Main',
                'part_number' => 'BOX',
                'pd' => 'PUNCH',
                'pcs_per_unit' => '1/Pcs',
                'ied_x' => '0',
                'ied_y' => '0',
                'completed_qty' => 0.00,
                'start_date' => '2025-06-01',
                'description' => 'Box production for DIA RUPIAH',
                'created_by' => 'System',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'wo_number' => '06-2025-01702',
                'so_number' => '06-2025-02253',
                'customer_name' => 'DIA RUPIAH',
                'plan_qty' => 50000.00,
                'due_date' => '2025-06-26',
                'status' => 'Active',
                'wo_status' => 'Active',
                'so_status' => 'Outstanding',
                'acr_number' => '000506',
                'mcs_number' => '0063879',
                'model' => '22819',
                'comp_number' => 'Main',
                'part_number' => 'BOX',
                'pd' => 'PUNCH',
                'pcs_per_unit' => '1/Pcs',
                'ied_x' => '0',
                'ied_y' => '0',
                'completed_qty' => 0.00,
                'start_date' => '2025-06-01',
                'description' => 'Box production for DIA RUPIAH',
                'created_by' => 'System',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'wo_number' => '06-2025-01701',
                'so_number' => '06-2025-02254',
                'customer_name' => 'DIA RUPIAH',
                'plan_qty' => 50000.00,
                'due_date' => '2025-06-25',
                'status' => 'Active',
                'wo_status' => 'Active',
                'so_status' => 'Outstanding',
                'acr_number' => '000506',
                'mcs_number' => '0063879',
                'model' => '22819',
                'comp_number' => 'Main',
                'part_number' => 'BOX',
                'pd' => 'PUNCH',
                'pcs_per_unit' => '1/Pcs',
                'ied_x' => '0',
                'ied_y' => '0',
                'completed_qty' => 0.00,
                'start_date' => '2025-06-01',
                'description' => 'Box production for DIA RUPIAH',
                'created_by' => 'System',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'wo_number' => '06-2025-01700',
                'so_number' => '06-2025-02268',
                'customer_name' => 'DIA RUPIAH',
                'plan_qty' => 25000.00,
                'due_date' => '2025-06-23',
                'status' => 'Active',
                'wo_status' => 'Active',
                'so_status' => 'Outstanding',
                'acr_number' => '000506',
                'mcs_number' => '0063879',
                'model' => '22819',
                'comp_number' => 'Main',
                'part_number' => 'BOX',
                'pd' => 'PUNCH',
                'pcs_per_unit' => '1/Pcs',
                'ied_x' => '0',
                'ied_y' => '0',
                'completed_qty' => 0.00,
                'start_date' => '2025-06-01',
                'description' => 'Box production for DIA RUPIAH',
                'created_by' => 'System',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'wo_number' => '06-2025-01699',
                'so_number' => '06-2025-02255',
                'customer_name' => 'DIA RUPIAH',
                'plan_qty' => 5000.00,
                'due_date' => '2025-06-21',
                'status' => 'Active',
                'wo_status' => 'Active',
                'so_status' => 'Outstanding',
                'acr_number' => '000506',
                'mcs_number' => '0063879',
                'model' => '22819',
                'comp_number' => 'Main',
                'part_number' => 'BOX',
                'pd' => 'PUNCH',
                'pcs_per_unit' => '1/Pcs',
                'ied_x' => '0',
                'ied_y' => '0',
                'completed_qty' => 0.00,
                'start_date' => '2025-06-01',
                'description' => 'Box production for DIA RUPIAH',
                'created_by' => 'System',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'wo_number' => '06-2025-01698',
                'so_number' => '06-2025-02264',
                'customer_name' => 'DIA RUPIAH',
                'plan_qty' => 5000.00,
                'due_date' => '2025-06-19',
                'status' => 'Active',
                'wo_status' => 'Active',
                'so_status' => 'Outstanding',
                'acr_number' => '000506',
                'mcs_number' => '0063879',
                'model' => '22819',
                'comp_number' => 'Main',
                'part_number' => 'BOX',
                'pd' => 'PUNCH',
                'pcs_per_unit' => '1/Pcs',
                'ied_x' => '0',
                'ied_y' => '0',
                'completed_qty' => 0.00,
                'start_date' => '2025-06-01',
                'description' => 'Box production for DIA RUPIAH',
                'created_by' => 'System',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'wo_number' => '06-2025-01697',
                'so_number' => '06-2025-02268',
                'customer_name' => 'DIA RUPIAH',
                'plan_qty' => 5000.00,
                'due_date' => '2025-06-16',
                'status' => 'Active',
                'wo_status' => 'Active',
                'so_status' => 'Outstanding',
                'acr_number' => '000506',
                'mcs_number' => '0063879',
                'model' => '22819',
                'comp_number' => 'Main',
                'part_number' => 'BOX',
                'pd' => 'PUNCH',
                'pcs_per_unit' => '1/Pcs',
                'ied_x' => '0',
                'ied_y' => '0',
                'completed_qty' => 0.00,
                'start_date' => '2025-06-01',
                'description' => 'Box production for DIA RUPIAH',
                'created_by' => 'System',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        DB::table('work_orders')->insert($workOrders);
    }
}
