-- Verify MC Gross M2 and Net M2 Calculations
-- This script helps verify that the automatic M2 calculations are working correctly
-- Note: MC_GROSS_M2_PER_PCS and MC_NET_M2_PER_PCS now use 6 decimal places precision

-- 1. Check all MC records with M2 values
SELECT 
    MCS_Num,
    AC_NUM,
    MODEL,
    SHEET_LENGTH,
    SHEET_WIDTH,
    PAPER_SIZE,
    CORR_OUT as CON_OUT,
    SLIT_OUT as CONV_OUT_1,
    DIE_OUT as CONV_OUT_2,
    JOIN_ as PCS_TO_JOINT,
    MC_GROSS_M2_PER_PCS,
    MC_NET_M2_PER_PCS,
    -- Manual calculation for verification (Gross M2)
    CASE 
        WHEN CORR_OUT > 0 AND SLIT_OUT > 0 AND DIE_OUT > 0 
        THEN ((SHEET_LENGTH * PAPER_SIZE * ISNULL(JOIN_, 1)) / (CORR_OUT * SLIT_OUT * DIE_OUT)) / 1000000
        ELSE NULL 
    END as CALCULATED_GROSS_M2,
    -- Manual calculation for verification (Net M2)
    CASE 
        WHEN SLIT_OUT > 0 AND DIE_OUT > 0 
        THEN (SHEET_LENGTH * SHEET_WIDTH) / 1000000 / (SLIT_OUT * DIE_OUT)
        ELSE NULL 
    END as CALCULATED_NET_M2
FROM MC
WHERE MC_GROSS_M2_PER_PCS IS NOT NULL 
   OR MC_NET_M2_PER_PCS IS NOT NULL
ORDER BY MCS_Num DESC;

-- 2. Check for discrepancies between stored and calculated values
SELECT 
    MCS_Num,
    AC_NUM,
    MODEL,
    MC_GROSS_M2_PER_PCS as STORED_GROSS_M2,
    CASE 
        WHEN CORR_OUT > 0 AND SLIT_OUT > 0 AND DIE_OUT > 0 
        THEN ((SHEET_LENGTH * PAPER_SIZE * ISNULL(JOIN_, 1)) / (CORR_OUT * SLIT_OUT * DIE_OUT)) / 1000000
        ELSE NULL 
    END as CALCULATED_GROSS_M2,
    ABS(MC_GROSS_M2_PER_PCS - 
        CASE 
            WHEN CORR_OUT > 0 AND SLIT_OUT > 0 AND DIE_OUT > 0 
            THEN ((SHEET_LENGTH * PAPER_SIZE * ISNULL(JOIN_, 1)) / (CORR_OUT * SLIT_OUT * DIE_OUT)) / 1000000
            ELSE 0 
        END
    ) as GROSS_M2_DIFFERENCE,
    MC_NET_M2_PER_PCS as STORED_NET_M2,
    CASE 
        WHEN SLIT_OUT > 0 AND DIE_OUT > 0 
        THEN (SHEET_LENGTH * SHEET_WIDTH) / 1000000 / (SLIT_OUT * DIE_OUT)
        ELSE NULL 
    END as CALCULATED_NET_M2,
    ABS(MC_NET_M2_PER_PCS - 
        CASE 
            WHEN SLIT_OUT > 0 AND DIE_OUT > 0 
            THEN (SHEET_LENGTH * SHEET_WIDTH) / 1000000 / (SLIT_OUT * DIE_OUT)
            ELSE 0 
        END
    ) as NET_M2_DIFFERENCE
FROM MC
WHERE MC_GROSS_M2_PER_PCS IS NOT NULL 
   OR MC_NET_M2_PER_PCS IS NOT NULL
HAVING ABS(MC_GROSS_M2_PER_PCS - 
        CASE 
            WHEN CORR_OUT > 0 AND SLIT_OUT > 0 AND DIE_OUT > 0 
            THEN ((SHEET_LENGTH * PAPER_SIZE * ISNULL(JOIN_, 1)) / (CORR_OUT * SLIT_OUT * DIE_OUT)) / 1000000
            ELSE 0 
        END
    ) > 0.0001
    OR ABS(MC_NET_M2_PER_PCS - 
        CASE 
            WHEN SLIT_OUT > 0 AND DIE_OUT > 0 
            THEN (SHEET_LENGTH * SHEET_WIDTH) / 1000000 / (SLIT_OUT * DIE_OUT)
            ELSE 0 
        END
    ) > 0.0001
ORDER BY GROSS_M2_DIFFERENCE DESC, NET_M2_DIFFERENCE DESC;

-- 3. Summary statistics
SELECT 
    COUNT(*) as TOTAL_MC_RECORDS,
    COUNT(MC_GROSS_M2_PER_PCS) as RECORDS_WITH_GROSS_M2,
    COUNT(MC_NET_M2_PER_PCS) as RECORDS_WITH_NET_M2,
    AVG(MC_GROSS_M2_PER_PCS) as AVG_GROSS_M2,
    AVG(MC_NET_M2_PER_PCS) as AVG_NET_M2,
    MIN(MC_GROSS_M2_PER_PCS) as MIN_GROSS_M2,
    MAX(MC_GROSS_M2_PER_PCS) as MAX_GROSS_M2,
    MIN(MC_NET_M2_PER_PCS) as MIN_NET_M2,
    MAX(MC_NET_M2_PER_PCS) as MAX_NET_M2
FROM MC;

-- 4. Check for missing calculation inputs
SELECT 
    MCS_Num,
    AC_NUM,
    MODEL,
    CASE WHEN SHEET_LENGTH IS NULL THEN 'Missing' ELSE 'OK' END as SHEET_LENGTH_STATUS,
    CASE WHEN SHEET_WIDTH IS NULL THEN 'Missing' ELSE 'OK' END as SHEET_WIDTH_STATUS,
    CASE WHEN PAPER_SIZE IS NULL THEN 'Missing' ELSE 'OK' END as PAPER_SIZE_STATUS,
    CASE WHEN CORR_OUT IS NULL THEN 'Missing' ELSE 'OK' END as CON_OUT_STATUS,
    CASE WHEN SLIT_OUT IS NULL THEN 'Missing' ELSE 'OK' END as CONV_OUT_1_STATUS,
    CASE WHEN DIE_OUT IS NULL THEN 'Missing' ELSE 'OK' END as CONV_OUT_2_STATUS,
    CASE WHEN JOIN_ IS NULL THEN 'Missing' ELSE 'OK' END as PCS_TO_JOINT_STATUS
FROM MC
WHERE SHEET_LENGTH IS NULL 
   OR SHEET_WIDTH IS NULL 
   OR PAPER_SIZE IS NULL 
   OR CORR_OUT IS NULL 
   OR SLIT_OUT IS NULL 
   OR DIE_OUT IS NULL
ORDER BY MCS_Num DESC;

-- 5. Recent MC updates with M2 values
SELECT TOP 20
    MCS_Num,
    AC_NUM,
    MODEL,
    SHEET_LENGTH,
    SHEET_WIDTH,
    PAPER_SIZE,
    MC_GROSS_M2_PER_PCS,
    MC_NET_M2_PER_PCS
FROM MC
WHERE MC_GROSS_M2_PER_PCS IS NOT NULL 
   OR MC_NET_M2_PER_PCS IS NOT NULL
ORDER BY MCS_Num DESC;

-- 6. Example calculation breakdown for a specific MCS
-- Replace 'YOUR_MCS_NUMBER' with actual MCS number
/*
SELECT 
    MCS_Num,
    '--- Input Values ---' as SECTION,
    SHEET_LENGTH,
    SHEET_WIDTH,
    PAPER_SIZE,
    CORR_OUT as CON_OUT,
    SLIT_OUT as CONV_OUT_1,
    DIE_OUT as CONV_OUT_2,
    JOIN_ as PCS_TO_JOINT,
    '--- Gross M2 Calculation ---' as GROSS_CALC,
    (SHEET_LENGTH * PAPER_SIZE * ISNULL(JOIN_, 1)) as GROSS_NUMERATOR,
    (CORR_OUT * SLIT_OUT * DIE_OUT) as GROSS_DENOMINATOR,
    ((SHEET_LENGTH * PAPER_SIZE * ISNULL(JOIN_, 1)) / (CORR_OUT * SLIT_OUT * DIE_OUT)) as GROSS_BEFORE_DIVISION,
    ((SHEET_LENGTH * PAPER_SIZE * ISNULL(JOIN_, 1)) / (CORR_OUT * SLIT_OUT * DIE_OUT)) / 1000000 as CALCULATED_GROSS_M2,
    MC_GROSS_M2_PER_PCS as STORED_GROSS_M2,
    '--- Net M2 Calculation ---' as NET_CALC,
    (SHEET_LENGTH * SHEET_WIDTH) as NET_NUMERATOR,
    (SLIT_OUT * DIE_OUT) as NET_DENOMINATOR,
    (SHEET_LENGTH * SHEET_WIDTH) / 1000000 as NET_BEFORE_DIVISION,
    ((SHEET_LENGTH * SHEET_WIDTH) / 1000000) / (SLIT_OUT * DIE_OUT) as CALCULATED_NET_M2,
    MC_NET_M2_PER_PCS as STORED_NET_M2
FROM MC
WHERE MCS_Num = 'YOUR_MCS_NUMBER';
*/
