<template>
  <AppLayout>
    <div class="p-6">
      <!-- Header Section -->
      <div class="mb-8">
        <div class="flex items-center justify-between">
          <div>
            <h1 class="text-3xl font-bold text-gray-900">View & Print Vehicle Classes</h1>
            <p class="mt-2 text-gray-600">View and print vehicle class definitions and specifications</p>
          </div>
          <div class="flex space-x-3">
            <button
              @click="printReport"
              class="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg flex items-center space-x-2 transition-colors"
            >
              <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"></path>
              </svg>
              <span>Print Report</span>
            </button>
            <button
              @click="exportToPDF"
              class="bg-red-600 hover:bg-red-700 text-white px-4 py-2 rounded-lg flex items-center space-x-2 transition-colors"
            >
              <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
              </svg>
              <span>Export PDF</span>
            </button>
            <button
              @click="exportToExcel"
              class="bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-lg flex items-center space-x-2 transition-colors"
            >
              <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
              </svg>
              <span>Export Excel</span>
            </button>
          </div>
        </div>
      </div>

      <!-- Report Information -->
      <div class="bg-white rounded-lg shadow-sm border border-gray-200 p-6 mb-6">
        <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div>
            <label class="block text-sm font-medium text-gray-700">Report Date</label>
            <p class="mt-1 text-sm text-gray-900">{{ formatDate(new Date()) }}</p>
          </div>
          <div>
            <label class="block text-sm font-medium text-gray-700">Total Records</label>
            <p class="mt-1 text-sm text-gray-900">{{ vehicleClasses.length }}</p>
          </div>
          <div>
            <label class="block text-sm font-medium text-gray-700">Generated By</label>
            <p class="mt-1 text-sm text-gray-900">{{ user?.name || 'System User' }}</p>
          </div>
        </div>
      </div>

      <!-- Vehicle Classes Report Table -->
      <div class="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden">
        <div class="overflow-x-auto">
          <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
              <tr>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  No.
                </th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Vehicle Class Code
                </th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Description
                </th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Standard Class Code
                </th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Volume (M³)
                </th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Capacity Weight (MT)
                </th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Created Date
                </th>
              </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
              <tr v-if="loading" class="animate-pulse">
                <td colspan="7" class="px-6 py-4 text-center">
                  <div class="flex items-center justify-center">
                    <svg class="animate-spin -ml-1 mr-3 h-5 w-5 text-blue-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                      <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                      <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                    </svg>
                    Loading vehicle classes...
                  </div>
                </td>
              </tr>
              <tr v-else-if="vehicleClasses.length === 0" class="text-center">
                <td colspan="7" class="px-6 py-8 text-gray-500">
                  <div class="flex flex-col items-center">
                    <svg class="w-12 h-12 text-gray-300 mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4"></path>
                    </svg>
                    <p class="text-lg font-medium">No vehicle classes found</p>
                    <p class="text-sm">No vehicle class data available for reporting.</p>
                  </div>
                </td>
              </tr>
              <tr v-else v-for="(vehicleClass, index) in vehicleClasses" :key="vehicleClass.id" class="hover:bg-gray-50 transition-colors">
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                  {{ index + 1 }}
                </td>
                <td class="px-6 py-4 whitespace-nowrap">
                  <div class="text-sm font-medium text-gray-900">{{ vehicleClass.VEHICLE_CLASS_CODE }}</div>
                </td>
                <td class="px-6 py-4 whitespace-nowrap">
                  <div class="text-sm text-gray-900">{{ vehicleClass.DESCRIPTION }}</div>
                </td>
                <td class="px-6 py-4 whitespace-nowrap">
                  <div class="text-sm text-gray-900">{{ vehicleClass.STANDART_CLASS_CODE }}</div>
                </td>
                <td class="px-6 py-4 whitespace-nowrap">
                  <div class="text-sm text-gray-900">{{ formatNumber(vehicleClass.VOLUME_M3) }}</div>
                </td>
                <td class="px-6 py-4 whitespace-nowrap">
                  <div class="text-sm text-gray-900">{{ formatNumber(vehicleClass.CAPACITY_WGT_MT) }}</div>
                </td>
                <td class="px-6 py-4 whitespace-nowrap">
                  <div class="text-sm text-gray-900">{{ formatDate(vehicleClass.created_at) }}</div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <!-- Summary Statistics -->
      <div v-if="vehicleClasses.length > 0" class="mt-8 grid grid-cols-1 md:grid-cols-3 gap-6">
        <div class="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
          <div class="flex items-center">
            <div class="flex-shrink-0">
              <svg class="h-8 w-8 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"></path>
              </svg>
            </div>
            <div class="ml-5 w-0 flex-1">
              <dl>
                <dt class="text-sm font-medium text-gray-500 truncate">Total Vehicle Classes</dt>
                <dd class="text-lg font-medium text-gray-900">{{ vehicleClasses.length }}</dd>
              </dl>
            </div>
          </div>
        </div>

        <div class="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
          <div class="flex items-center">
            <div class="flex-shrink-0">
              <svg class="h-8 w-8 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4"></path>
              </svg>
            </div>
            <div class="ml-5 w-0 flex-1">
              <dl>
                <dt class="text-sm font-medium text-gray-500 truncate">Average Volume</dt>
                <dd class="text-lg font-medium text-gray-900">{{ formatNumber(averageVolume) }} M³</dd>
              </dl>
            </div>
          </div>
        </div>

        <div class="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
          <div class="flex items-center">
            <div class="flex-shrink-0">
              <svg class="h-8 w-8 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path>
              </svg>
            </div>
            <div class="ml-5 w-0 flex-1">
              <dl>
                <dt class="text-sm font-medium text-gray-500 truncate">Average Capacity</dt>
                <dd class="text-lg font-medium text-gray-900">{{ formatNumber(averageCapacity) }} MT</dd>
              </dl>
            </div>
          </div>
        </div>
      </div>

      <!-- Print Styles (Hidden by default) -->
      <div id="print-content" class="hidden">
        <div class="print-header">
          <h1 class="text-2xl font-bold text-center mb-4">Vehicle Class Report</h1>
          <div class="text-center text-sm text-gray-600 mb-6">
            Generated on: {{ formatDate(new Date()) }} | Total Records: {{ vehicleClasses.length }}
          </div>
        </div>
        
        <table class="w-full border-collapse border border-gray-400">
          <thead>
            <tr class="bg-gray-100">
              <th class="border border-gray-400 px-2 py-1 text-left">No.</th>
              <th class="border border-gray-400 px-2 py-1 text-left">Vehicle Class Code</th>
              <th class="border border-gray-400 px-2 py-1 text-left">Description</th>
              <th class="border border-gray-400 px-2 py-1 text-left">Standard Class Code</th>
              <th class="border border-gray-400 px-2 py-1 text-left">Volume (M³)</th>
              <th class="border border-gray-400 px-2 py-1 text-left">Capacity Weight (MT)</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="(vehicleClass, index) in vehicleClasses" :key="vehicleClass.id">
              <td class="border border-gray-400 px-2 py-1">{{ index + 1 }}</td>
              <td class="border border-gray-400 px-2 py-1">{{ vehicleClass.VEHICLE_CLASS_CODE }}</td>
              <td class="border border-gray-400 px-2 py-1">{{ vehicleClass.DESCRIPTION }}</td>
              <td class="border border-gray-400 px-2 py-1">{{ vehicleClass.STANDART_CLASS_CODE }}</td>
              <td class="border border-gray-400 px-2 py-1">{{ formatNumber(vehicleClass.VOLUME_M3) }}</td>
              <td class="border border-gray-400 px-2 py-1">{{ formatNumber(vehicleClass.CAPACITY_WGT_MT) }}</td>
            </tr>
          </tbody>
        </table>
      </div>

      <!-- Toast Container -->
      <ToastContainer />
    </div>
  </AppLayout>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { useToast } from '@/Composables/useToast'
import AppLayout from '@/Layouts/AppLayout.vue'
import ToastContainer from '@/Components/ToastContainer.vue'

const { addToast } = useToast()

// Props
const props = defineProps({
  vehicleClasses: {
    type: Array,
    default: () => []
  },
  user: {
    type: Object,
    default: () => null
  }
})

// Reactive data
const loading = ref(false)

// Computed properties
const averageVolume = computed(() => {
  if (props.vehicleClasses.length === 0) return 0
  const total = props.vehicleClasses.reduce((sum, vc) => sum + parseFloat(vc.VOLUME_M3), 0)
  return total / props.vehicleClasses.length
})

const averageCapacity = computed(() => {
  if (props.vehicleClasses.length === 0) return 0
  const total = props.vehicleClasses.reduce((sum, vc) => sum + parseFloat(vc.CAPACITY_WGT_MT), 0)
  return total / props.vehicleClasses.length
})

// Methods
const formatNumber = (number) => {
  return parseFloat(number).toFixed(2)
}

const formatDate = (date) => {
  return new Date(date).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  })
}

const printReport = () => {
  const printContent = document.getElementById('print-content')
  const originalContent = document.body.innerHTML
  
  document.body.innerHTML = printContent.innerHTML
  
  window.print()
  
  document.body.innerHTML = originalContent
  window.location.reload()
  
  addToast('Report printed successfully', 'success')
}

const exportToPDF = () => {
  // This would typically use a library like jsPDF or send a request to generate PDF
  addToast('PDF export functionality would be implemented here', 'info')
}

const exportToExcel = () => {
  const csvContent = [
    ['No.', 'Vehicle Class Code', 'Description', 'Standard Class Code', 'Volume (M³)', 'Capacity Weight (MT)', 'Created Date'],
    ...props.vehicleClasses.map((vc, index) => [
      index + 1,
      vc.VEHICLE_CLASS_CODE,
      vc.DESCRIPTION,
      vc.STANDART_CLASS_CODE,
      vc.VOLUME_M3,
      vc.CAPACITY_WGT_MT,
      formatDate(vc.created_at)
    ])
  ].map(row => row.join(',')).join('\n')
  
  const blob = new Blob([csvContent], { type: 'text/csv' })
  const url = window.URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `vehicle-classes-report-${new Date().toISOString().split('T')[0]}.csv`
  a.click()
  window.URL.revokeObjectURL(url)
  
  addToast('Report exported to Excel successfully', 'success')
}

// Lifecycle
onMounted(() => {
  // Component is ready
})
</script>

<style scoped>
@media print {
  .no-print {
    display: none !important;
  }
  
  #print-content {
    display: block !important;
  }
  
  body {
    font-size: 12px;
    line-height: 1.4;
  }
  
  table {
    width: 100%;
    border-collapse: collapse;
  }
  
  th, td {
    border: 1px solid #000;
    padding: 4px;
    text-align: left;
  }
  
  th {
    background-color: #f0f0f0;
    font-weight: bold;
  }
}
</style>
