<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class UpdateMC extends Model
{
    use HasFactory;

    protected $table = 'MC';

    public $timestamps = false;
    protected $primaryKey = null;
    public $incrementing = false;

    protected $fillable = [
        'AC_NUM','AC_NAME','STS','REASON','COMP','P_DESIGN','MCS_Num','MODEL','FLUTE',
        'SO_PQ1','SO_PQ2','SO_PQ3','SO_PQ4','SO_PQ5',
        'WO_PQ1','WO_PQ2','WO_PQ3','WO_PQ4','WO_PQ5',
        'S_TOOL','COAT','TAPE','COLOR1','COLOR2','COLOR3','COLOR4','COLOR5','COLOR6','COLOR7',
        'PRINTING_BLOCK_NO','DIECUT_MOULD_NO','FSH','SWIRE','GLUEING','WRAPPING','HAND_HOLE','ROTARY_DC','FB_PRINTING','STRING_TYPE','ITEM_REMARK','UNIT','CURRENCY','PART_NO',
        'MSP1_MCH','MSP1_UP','MSP1_SPECIAL_INST','MSP2_MCH','MSP2_UP','MSP2_SPECIAL_INST','MSP3_MCH','MSP3_UP','MSP3_SPECIAL_INST','MSP4_MCH','MSP4_UP','MSP4_SPECIAL_INST',
        'MSP5_MCH','MSP5_UP','MSP5_SPECIAL_INST','MSP6_MCH','MSP6_UP','MSP6_SPECIAL_INST','MSP7_MCH','MSP7_UP','MSP7_SPECIAL_INST','MSP8_MCH','MSP8_UP','MSP8_SPECIAL_INST',
        'MSP9_MCH','MSP9_UP','MSP9_SPECIAL_INST','MSP10_MCH','MSP10_UP','MSP10_SPECIAL_INST','MSP11_MCH','MSP11_UP','MSP11_SPECIAL_INST','MSP12_MCH','MSP12_UP','MSP12_SPECIAL_INST',
        'MC_SPECIAL_INST1','MC_SPECIAL_INST2','MC_SPECIAL_INST3','MC_SPECIAL_INST4','MC_MORE_DESCRIPTION_1','MC_MORE_DESCRIPTION_2','MC_MORE_DESCRIPTION_3','MC_MORE_DESCRIPTION_4','MC_MORE_DESCRIPTION_5',
        'INT_LENGTH','INT_WIDTH','INT_HEIGHT','EXT_LENGTH','EXT_WIDTH','EXT_HEIGHT','SHEET_LENGTH','SHEET_WIDTH','PAPER_SIZE','CORR_OUT','SLIT_OUT','DIE_OUT','JOIN_','NEST_SLOT','CREASE',
        'SL1','SL2','SL3','SL4','SL5','SL6','SL7','SL8','TOTAL_SL','SW1','SW2','SW3','SW4','SW5','SW6','SW7','SW8','TOTAL_SW',
        'COLOR1_AREA_PERCENT','COLOR2_AREA_PERCENT','COLOR3_AREA_PERCENT','COLOR4_AREA_PERCENT','COLOR5_AREA_PERCENT','COLOR6_AREA_PERCENT','COLOR7_AREA_PERCENT',
        'DC_SHT_L','DC_SHT_W','DC_MOULD_L','DC_MOULD_W','SWIRE_PCS','PEEL_OFF_PERCENT','PCS_PER_BLD','STRING_TYPE_VALUE','BLD_PER_PLD','PCS_SET','UNIT_PRICE',
        'MC_GROSS_M2_PER_PCS','MC_NET_M2_PER_PCS','MC_GROSS_KG_PER_SET','MC_NET_KG_PER_PCS','TOTAL_COLOR',
    ];
}
